version: '3'

services:
  neo4j:
    build: ./neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
  neo4j-example-service:
    build: ./neo4j-example-service
    ports:
      - "8080:8080"
    depends_on:
      - neo4j